using ProjectWorldCup;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace Tests.WorldCup
{
    public class LeagueTest
    {
        [Fact]
        public void PremierLeague_2020_2021()
        {
            var league = new League
            {
                Name = "PremierLeague 2020-2021",
                Teams = new(),
                Matches = new(),
            };

            #region Teams
            league.Teams.Add(new Team { Id = "MCI", Name = "Manchester City" });
            league.Teams.Add(new Team { Id = "MUN", Name = "Manchester United" });
            league.Teams.Add(new Team { Id = "LIV", Name = "Liverpool" });
            league.Teams.Add(new Team { Id = "CHE", Name = "Chelsea" });
            league.Teams.Add(new Team { Id = "LEI", Name = "Leicester City" });
            league.Teams.Add(new Team { Id = "WHU", Name = "West Ham United" });
            league.Teams.Add(new Team { Id = "TOT", Name = "Tottenham Hotspur" });
            league.Teams.Add(new Team { Id = "ARS", Name = "Arsenal" });
            league.Teams.Add(new Team { Id = "LEE", Name = "Leeds United" });
            league.Teams.Add(new Team { Id = "EVE", Name = "Everton" });
            league.Teams.Add(new Team { Id = "AVL", Name = "Aston Villa" });
            league.Teams.Add(new Team { Id = "NEW", Name = "Newcastle United" });
            league.Teams.Add(new Team { Id = "WOL", Name = "Wolverhampton Wanderers" });
            league.Teams.Add(new Team { Id = "CRY", Name = "Crystal Palace" });
            league.Teams.Add(new Team { Id = "SOU", Name = "Southampton" });
            league.Teams.Add(new Team { Id = "BHA", Name = "Brighton and Hove Albion" });
            league.Teams.Add(new Team { Id = "BUR", Name = "Burnley" });
            league.Teams.Add(new Team { Id = "FUL", Name = "Fulham" });
            league.Teams.Add(new Team { Id = "WBA", Name = "West Bromwich Albion" });
            league.Teams.Add(new Team { Id = "SHU", Name = "Sheffield United" });
            #endregion

            #region Matches
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("BHA"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("CHE"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("NEW"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("WBA"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("TOT"), HomeScore = 2, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("CRY"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("EVE"), HomeScore = 5, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("BUR"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("SOU"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("MUN"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("LIV"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("WHU"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("ARS"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("WOL"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("SHU"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("AVL"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("LEI"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("MCI"), HomeScore = 3, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("FUL"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("LEE"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("SHU"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("LIV"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("WOL"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("AVL"), HomeScore = 3, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("WHU"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("FUL"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("LEE"), HomeScore = 0, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("MCI"), HomeScore = 3, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("LIV"), HomeScore = 2, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("EVE"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("ARS"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("CRY"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("LEI"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("BUR"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("WBA"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("EVE"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("MUN"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("BHA"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("SOU"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("CHE"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("CRY"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("TOT"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("NEW"), HomeScore = 2, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("WHU"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("WOL"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("SHU"), HomeScore = 4, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("ARS"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("AVL"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("FUL"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("LEE"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("MCI"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("LEI"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("CRY"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("WBA"), HomeScore = 2, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("MUN"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("BUR"), HomeScore = 0, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("BHA"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("CHE"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("NEW"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("EVE"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("WBA"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("MCI"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("SOU"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("BHA"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("LIV"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("BUR"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("FUL"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("SHU"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("WHU"), HomeScore = 3, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("TOT"), HomeScore = 2, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("EVE"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("SOU"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("ARS"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("MUN"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("LEI"), HomeScore = 3, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("NEW"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("CHE"), HomeScore = 1, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("AVL"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("LEE"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("WOL"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("WHU"), HomeScore = 2, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("CRY"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("BHA"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("FUL"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("TOT"), HomeScore = 2, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("BUR"), HomeScore = 3, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("LIV"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("MCI"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("SHU"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("WBA"), HomeScore = 2, AwayScore = 5, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("TOT"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("ARS"), HomeScore = 3, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("NEW"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("LEE"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("LIV"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("WHU"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("TOT"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("SHU"), HomeScore = 5, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("BHA"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("MCI"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("BUR"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("WBA"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("CHE"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("AVL"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("SOU"), HomeScore = 5, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("LEE"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("EVE"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("CRY"), HomeScore = 4, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("MUN"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("FUL"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("NEW"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("LEI"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("WOL"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("SOU"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("ARS"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("CHE"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("TOT"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("EVE"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("MUN"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("LEI"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("AVL"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("WOL"), HomeScore = 4, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("SOU"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("LIV"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("MUN"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("BUR"), HomeScore = 4, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("FUL"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("ARS"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("WOL"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("AVL"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("BHA"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("WHU"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("SOU"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("CRY"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("NEW"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("MCI"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("LEI"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("TOT"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("SHU"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("EVE"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("WBA"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("CHE"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("LEE"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("MCI"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("FUL"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("NEW"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("SHU"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("FUL"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("LEE"), HomeScore = 4, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("MUN"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("WOL"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("AVL"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("TOT"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("BUR"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("LIV"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("CRY"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("CHE"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("MCI"), HomeScore = 1, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("LEI"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("WBA"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("EVE"), HomeScore = 3, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("WHU"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("BHA"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("SOU"), HomeScore = 3, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("ARS"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("CHE"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("WHU"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("BHA"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("EVE"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("MCI"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("LEI"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("SOU"), HomeScore = 9, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("CRY"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("WBA"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("ARS"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("TOT"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("LIV"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("LEE"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("BUR"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("AVL"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("MUN"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("WOL"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("SHU"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("FUL"), HomeScore = 2, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("NEW"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("LIV"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("LEI"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("SHU"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("FUL"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("AVL"), HomeScore = 3, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("WOL"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("ARS"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("MCI"), HomeScore = 0, AwayScore = 5, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("WHU"), HomeScore = 2, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("LEE"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("NEW"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("BUR"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("MUN"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("AVL"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("CHE"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("WBA"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("NEW"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("CRY"), HomeScore = 4, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("MUN"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("TOT"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("SOU"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("CHE"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("BHA"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("BUR"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("WBA"), HomeScore = 2, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("CRY"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("FUL"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("BHA"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("MUN"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("EVE"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("NEW"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("LIV"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("MCI"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("LEI"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("ARS"), HomeScore = 0, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("WOL"), HomeScore = 3, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("SHU"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("LEE"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("AVL"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("WHU"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("LIV"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("WOL"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("ARS"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("SHU"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("WHU"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("LEE"), HomeScore = 0, AwayScore = 5, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("AVL"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("LEI"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("TOT"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("WBA"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("BHA"), HomeScore = 2, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("BUR"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("NEW"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("EVE"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("CHE"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("CRY"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("SOU"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("MUN"), HomeScore = 2, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("WHU"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("WOL"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("AVL"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("LEE"), HomeScore = 6, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("LEI"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("SHU"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("FUL"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("ARS"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("MCI"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("LIV"), HomeScore = 0, AwayScore = 7, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("MUN"), HomeScore = 2, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("BUR"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("BHA"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("TOT"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("CRY"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("SOU"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("NEW"), HomeScore = 5, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("EVE"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("WBA"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("CHE"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("BUR"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("BHA"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("LIV"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("TOT"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("SHU"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("CHE"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("MCI"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("WBA"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("AVL"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("WHU"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("SOU"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("WOL"), HomeScore = 4, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("ARS"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("LEI"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("CRY"), HomeScore = 1, AwayScore = 5, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("LEE"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("MUN"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("FUL"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("EVE"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("AVL"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("FUL"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("WOL"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("TOT"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("MUN"), HomeScore = 2, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("SHU"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("LEE"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("BUR"), HomeScore = 5, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("LIV"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("NEW"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("SOU"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("CRY"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("LEI"), HomeScore = 3, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("ARS"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("WHU"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("EVE"), HomeScore = 2, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("WBA"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("MCI"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("BHA"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("CHE"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("AVL"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("LIV"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("WOL"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("TOT"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("FUL"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("SHU"), HomeScore = 4, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("LEE"), HomeScore = 4, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("MUN"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("NEW"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("BUR"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("LEI"), HomeScore = 1, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("WBA"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("BHA"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("ARS"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("EVE"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("SOU"), HomeScore = 3, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("WHU"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("CHE"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("MCI"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("CRY"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("TOT"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("WBA"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("LEI"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("NEW"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("EVE"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("SHU"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("CHE"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("CRY"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("MCI"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("LEE"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("WOL"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("BUR"), HomeScore = 0, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("AVL"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("WHU"), HomeScore = 3, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("BHA"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("FUL"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("MUN"), HomeScore = 1, AwayScore = 4, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("ARS"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("SOU"), HomeScore = 3, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("LIV"), HomeScore = 2, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("LIV"), HomeScore = 7, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("TOT"), HomeScore = 1, AwayScore = 6, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("SHU"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("FUL"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("WHU"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("WBA"), HomeScore = 2, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("BUR"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("MCI"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("BHA"), HomeScore = 4, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("CRY"), HomeScore = 4, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("ARS"), HomeScore = 3, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("AVL"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("WOL"), HomeScore = 4, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MCI"), AwayTeam = league.FindTeam("LEI"), HomeScore = 2, AwayScore = 5, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("NEW"), HomeScore = 1, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("LEE"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BUR"), AwayTeam = league.FindTeam("SOU"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("CHE"), HomeScore = 3, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("EVE"), HomeScore = 1, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("MUN"), HomeScore = 2, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WOL"), AwayTeam = league.FindTeam("MCI"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("AVL"), AwayTeam = league.FindTeam("SHU"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEI"), AwayTeam = league.FindTeam("BUR"), HomeScore = 4, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CHE"), AwayTeam = league.FindTeam("LIV"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("NEW"), AwayTeam = league.FindTeam("BHA"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SOU"), AwayTeam = league.FindTeam("TOT"), HomeScore = 2, AwayScore = 5, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("ARS"), AwayTeam = league.FindTeam("WHU"), HomeScore = 2, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("MUN"), AwayTeam = league.FindTeam("CRY"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LEE"), AwayTeam = league.FindTeam("FUL"), HomeScore = 4, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("EVE"), AwayTeam = league.FindTeam("WBA"), HomeScore = 5, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("BHA"), AwayTeam = league.FindTeam("CHE"), HomeScore = 1, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("SHU"), AwayTeam = league.FindTeam("WOL"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("TOT"), AwayTeam = league.FindTeam("EVE"), HomeScore = 0, AwayScore = 1, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WBA"), AwayTeam = league.FindTeam("LEI"), HomeScore = 0, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("WHU"), AwayTeam = league.FindTeam("NEW"), HomeScore = 0, AwayScore = 2, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("LIV"), AwayTeam = league.FindTeam("LEE"), HomeScore = 4, AwayScore = 3, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("CRY"), AwayTeam = league.FindTeam("SOU"), HomeScore = 1, AwayScore = 0, });
            league.Matches.Add(new Match { HomeTeam = league.FindTeam("FUL"), AwayTeam = league.FindTeam("ARS"), HomeScore = 0, AwayScore = 3, });
            #endregion

            var stands = league.Stands;

            Assert.Equal(league.Teams.Count, stands.Count);

            #region Rank 순위
            var rank = 0;
            Assert.Equal("MCI", stands[rank++].Team.Id);
            Assert.Equal("MUN", stands[rank++].Team.Id);
            Assert.Equal("LIV", stands[rank++].Team.Id);
            Assert.Equal("CHE", stands[rank++].Team.Id);
            Assert.Equal("LEI", stands[rank++].Team.Id);
            Assert.Equal("WHU", stands[rank++].Team.Id);
            Assert.Equal("TOT", stands[rank++].Team.Id);
            Assert.Equal("ARS", stands[rank++].Team.Id);
            Assert.Equal("LEE", stands[rank++].Team.Id);
            Assert.Equal("EVE", stands[rank++].Team.Id);
            Assert.Equal("AVL", stands[rank++].Team.Id);
            Assert.Equal("NEW", stands[rank++].Team.Id);
            Assert.Equal("WOL", stands[rank++].Team.Id);
            Assert.Equal("CRY", stands[rank++].Team.Id);
            Assert.Equal("SOU", stands[rank++].Team.Id);
            Assert.Equal("BHA", stands[rank++].Team.Id);
            Assert.Equal("BUR", stands[rank++].Team.Id);
            Assert.Equal("FUL", stands[rank++].Team.Id);
            Assert.Equal("WBA", stands[rank++].Team.Id);
            Assert.Equal("SHU", stands[rank++].Team.Id);

            rank = 0;
            Assert.Equal(1, stands[rank++].Rank);
            Assert.Equal(2, stands[rank++].Rank);
            Assert.Equal(3, stands[rank++].Rank);
            Assert.Equal(4, stands[rank++].Rank);
            Assert.Equal(5, stands[rank++].Rank);
            Assert.Equal(6, stands[rank++].Rank);
            Assert.Equal(7, stands[rank++].Rank);
            Assert.Equal(8, stands[rank++].Rank);
            Assert.Equal(9, stands[rank++].Rank);
            Assert.Equal(10, stands[rank++].Rank);
            Assert.Equal(11, stands[rank++].Rank);
            Assert.Equal(12, stands[rank++].Rank);
            Assert.Equal(13, stands[rank++].Rank);
            Assert.Equal(14, stands[rank++].Rank);
            Assert.Equal(15, stands[rank++].Rank);
            Assert.Equal(16, stands[rank++].Rank);
            Assert.Equal(17, stands[rank++].Rank);
            Assert.Equal(18, stands[rank++].Rank);
            Assert.Equal(19, stands[rank++].Rank);
            Assert.Equal(20, stands[rank++].Rank);
            #endregion

            #region Point 승점
            rank = 0;
            Assert.Equal(86, stands[rank++].Point);
            Assert.Equal(74, stands[rank++].Point);
            Assert.Equal(69, stands[rank++].Point);
            Assert.Equal(67, stands[rank++].Point);
            Assert.Equal(66, stands[rank++].Point);
            Assert.Equal(65, stands[rank++].Point);
            Assert.Equal(62, stands[rank++].Point);
            Assert.Equal(61, stands[rank++].Point);
            Assert.Equal(59, stands[rank++].Point);
            Assert.Equal(59, stands[rank++].Point);
            Assert.Equal(55, stands[rank++].Point);
            Assert.Equal(45, stands[rank++].Point);
            Assert.Equal(45, stands[rank++].Point);
            Assert.Equal(44, stands[rank++].Point);
            Assert.Equal(43, stands[rank++].Point);
            Assert.Equal(41, stands[rank++].Point);
            Assert.Equal(39, stands[rank++].Point);
            Assert.Equal(28, stands[rank++].Point);
            Assert.Equal(26, stands[rank++].Point);
            Assert.Equal(23, stands[rank++].Point);
            #endregion
        }
    }

    public static class LeagueExtensions
    {
        public static Team FindTeam(this League league, string id)
        {
            return league.Teams.FirstOrDefault(x => x.Id == id);
        }
    }
}
