global using JkwExtensions;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using Common;
global using Microsoft.AspNetCore.Components;
global using Newtonsoft.Json.Converters;
global using System;
global using System.Text.RegularExpressions;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using System.IO;
global using Microsoft.Extensions.Logging;
global using Microsoft.AspNetCore.Components.Routing;
global using ProjectWorldCup.FifaLibrary;
global using MudBlazor;

namespace ProjectWorldCup;
